import React from 'react'

const About = () => {
  return (
    <div>
      ここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAboutここにAbout
    </div>
  )
}

export default About

